googleapis/packman

lib/api_repo.js, lib/packager.js, templates/commonpb/python/MANIFEST.in, templates/python/MANIFEST.in, test/api_repo.js, test/packager.js
- Python packages should incorporate a MANIFEST.in and optionally requirements.txt; this
adds support for that.
Also, simplifies the code for specifying what templates need to be
transformed per-language by allowing them be absent.  If a template is
specified for a language, but is not present, it is skipped.
Change-Id: I77ad8dc93337799f0c0ddeee82ddee51575aefbe
=> Add support for including MANIFEST.in

.travis.yml, test/api_repo.js
Noticed that npm run lint actually reports missing semicolons.
Also modified travis.yml to run linting.
=> Minor style fixes.

bin/gen-api-package, lib/api_repo.js, lib/packager.js, templates/commonpb/java/build-alt.gradle.mustache, templates/java/build-alt.gradle.mustache
Fixes #20
- it adds experimental_alt_java flag to gen-api-package that modifies
java package generation
- normally, the generated gradle file builds a package that only
contains protos
- when the flag is set, the generated gradle file builds a package from
the java source generated running the protoc
Change-Id: Iae50a2192595774502ad368196de507ad90e437a
=> Adds support for java packages with compiled code

templates/gax/python/README.rst.mustache, templates/gax/python/docs/starting.rst.mustache, templates/gax/ruby/README.md.mustache
Reported to recommend gcloud beta auth application-default login
rather than gcloud auth login. Considering the beta status,
I think we should mention both.
This fixes #28
=> Update to mention new auth method

config/api_defaults.yml, lib/packager.js, templates/gax/ruby/README.md.mustache
Because Gapic/Ruby now generates 'doc' files, the generated
package document contains tons of classes and it's hard for
users to find where they can start.
This patch scans the files under lib/ and generates the list
of core classes. This logic assumes that Gapic/Ruby generates
the 'doc' files under a directory 'doc/'.
Upgrading to 0.6.3 considering I've uploaded some packages
to 0.6.2 in rubygems.org.
Fixes #32
=> Ruby: list the core API classes in README.md

bin/gen-api-package, config/dependencies.yml, lib/api_repo.js, lib/packager.js, templates/nodejs/package.json.mustache, templates/nodejs/service.js.mustache, test/fixtures/proto-based/nodejs/README.md, test/fixtures/proto-based/nodejs/package.json, test/fixtures/proto-based/nodejs/service.js, test/packager.js
Currently nodejs grpc client uses pbjs to convert the .proto files
into JSON format. However the generated JSON format / loaded data
does not work with grpc (see #35).
The new client instead copies .proto files to the output directory,
and uses protobufjs.loadProtoFile. gRPC actually works well with
this approach.
Fixes #35
=> Introduce a new type of grpc client for nodejs

lib/api_repo.js, test/api_repo.js
These files are not bundled in ProtoBuf.js, so they should be
copied as well, but this code gently ignore these files because
they are not in the includePath.
Added the code to copy them, and prints warning message in case
some unexpected files are included.
=> Add google/protobuf files to the dependency.

lib/api_repo.js
The grpc plugin command-line is omitted when this flag is specified,
thus --grpc_out should also be omitted.
=> Fix a failure of packman for --build_common_protos flag.

config/api_defaults.yml, config/dependencies.yml, templates/gax/nodejs/package.json.mustache
- Update google-gax versions
- Update grpc-nodejs to 0.15.0
- Remove unnecessary dependencies from gapic-generated nodejs packages.
=> Update dependency version

config/api_defaults.yml, config/dependencies.yml
This also changes the dependency on gax, which is updated to
0.4.1 by https://github.com/googleapis/gax-ruby/pull/34
=> Update Ruby gRPC dependency to 0.15.0

package.json, templates/python/MANIFEST.in
Adds the LICENSE file into the MANIFEST.in used for gRPC Python
packages.
=> Include LICENSE in Python gRPC packages

templates/java/build-alt.gradle.mustache
Packman was using incompatible versions of protobuf which causes compile erros in the generated grpc package.
=> Fix protoc version in java build template

config/dependencies.yml, package.json
Latest codegen relies on new version of GAX.
=> Update Python GAX dependency

lib/api_repo.js
In JS, replace() with a string will replace only the first
occurrence, thus this is going to fail if multiple words are
involved (like 'google-cloud-language').
=> replace to replace all occurrences.

templates/commonpb/java/build-alt.gradle.mustache, templates/commonpb/java/build.gradle.mustache, templates/commonpb/java/settings.gradle.mustache, templates/commonpb/python/setup.py.mustache, templates/commonpb/ruby/gemspec.mustache, templates/gax/nodejs/README.md.mustache, templates/gax/nodejs/index.js.mustache, templates/gax/nodejs/package.json.mustache, templates/gax/python/README.rst.mustache, templates/gax/python/requirements.txt.mustache, templates/gax/python/setup.py.mustache, templates/gax/ruby/README.md.mustache, templates/gax/ruby/gemspec.mustache, templates/java/build-alt.gradle.mustache, templates/java/build.gradle.mustache, templates/java/settings.gradle.mustache, templates/nodejs/README.md.mustache, templates/nodejs/package.json.mustache, templates/objc/podspec.mustache, templates/php/README.md.mustache, templates/php/composer.json.mustache, templates/python/README.rst.mustache, templates/python/setup.py.mustache, templates/ruby/gemspec.mustache
Don't think we ever want HTML escaping, and having it on by default
causes problems whenever API names contain, e.g., a hyphen.
=> Disable HTML escaping across all templates

README.md, bin/gen-api-package, lib/api_repo.js, test/api_repo.js
We are not using this flag anywhere, and it's better not to
have special logic for Google APIs. In the implementation, a
variable of the same name remains because it is necessary to support
the GitHub zip archive use case.
=> Kill the isGoogleApi flag

config/dependencies.yml, templates/gax/python/requirements.txt.mustache, templates/gax/python/setup.py.mustache
Previously, the version was pegged. This way should prevent issues
like https://github.com/GoogleCloudPlatform/gcloud-python/issues/1979
FYI @bjwatson
=> Allow a range of point versions for gax-python

lib/packager.js, templates/gax/nodejs/index.js.mustache, test/fixtures/gax/nodejs/index.js
This is necessary due to the change in https://github.com/googleapis/toolkit/pull/351
=> Fix gax-generated code path from src to lib.

templates/java/build-alt.gradle.mustache, templates/java/build.gradle.mustache, test/fixtures/java/build.gradle
This PR should fix: https://github.com/googleapis/packman/issues/68, https://github.com/googleapis/packman/issues/70
=> Fix group name of generated grpc java package.

config/api_defaults.yml, config/dependencies.yml, package.json
Corresponds to https://github.com/googleapis/gax-python/pull/122
=> Bump Python GAX version

bin/gen-api-package, config/api_defaults.yml, config/dependencies.yml, lib/api_repo.js, templates/java/build-alt.gradle.mustache, templates/java/build.gradle.mustache, test/fixtures/java/build.gradle, test/packager.js
This is so that we can switch artman to use packman for JavaCorePipeline instead of the proto generation inside artman.
=> Java: supporting common protos package with compiled classes

README.md, bin/gen-api-package, lib/api_repo.js, test/api_repo.js
This allows packman to support languages like Python, where the
official way of doing grpc codegen is through a Python wrapper around
protoc.
Updates googleapis/gax-python#126
=> Allow protoc to be injected

bin/gen-api-package, config/api_defaults.yml, lib/api_repo.js, templates/java/build-alt.gradle.mustache
This allows common protos to use the same code path as grpc packages, so
the build_common_protos option doesn't need to be passed.
=> Java generation: supporting dependencies option

lib/api_repo.js
protoc commandline invocation fails when protoCompilerArgs is
empty (i.e. prevent adding an empty string '' as a parameter).
Fixes #101.
=> Fix protoc arguments.

.gitignore, bin/gen-api-package, config/api_defaults.yml, config/dependencies.yml, lib/api_repo.js, test/api_repo.js, test/fixtures/fake_protoc
* Use --grpc_python_out argument for Python, per https://github.com/grpc/grpc/issues/7857#issuecomment-243503869.
* Ensure that `gen-api-package` returns a non-zero status code when it fails (needed for remote pipeline to properly report a failure)
=> Fix GRPC python gen issues

config/common_protos.yml, config/dependencies.yml, templates/commonpb/python/setup.py.mustache
See for historical context:
https://bitbucket.org/seewind/grpc/issues/1/naming-collision-with-grpc-grpc
Updates https://github.com/GoogleCloudPlatform/gcloud-python/issues/2238
=> Python depends on grpcio, rather than grpc.

config/common_protos.yml, config/dependencies.yml, templates/commonpb/python/setup.py.mustache, templates/python/setup.py.mustache, test/fixtures/python/setup.py
Updates https://github.com/GoogleCloudPlatform/gcloud-python/issues/2117
NB I deliberately did not add the optional `[grpc]` dependency to the `gax-google-*` packages. They'll currently get `grpcio` transitively from the `grpc-google-*` packages, and I'm thinking forward to when `gax-google-*` might also support HTTP/JSON (and thus not need a gRPC dependency).
=> Make grpcio dep optional for Python googleapis-common-protos

config/common_protos.yml, config/dependencies.yml, lib/api_repo.js, test/api_repo.js, test/fixtures/fake_protoc
Updates https://github.com/GoogleCloudPlatform/google-cloud-python/issues/1893#issuecomment-245366078
https://github.com/grpc/grpc/issues/8056 is a proposal to fix this issue in gRPC (FYI @jmuk)
=> Only build common protos with --grpc option for LRO.

lib/packager.js
The test succeeded unexpectedly because the test code handles
the data in a different way. Fixed both of them.
=> NodeJS fix -- glob.glob returns the relative path.

templates/gax/nodejs/index.js.mustache, templates/gax/nodejs/src/index.js.mustache, test/fixtures/gax/nodejs/src/index.js, test/fixtures/gax/nodejs/src/v2/index.js
- 'use strict' is unnecessary but better to exist.
- it's better to avoid starting the license comment with /**
=> Update nodejs gax template.

config/api_defaults.yml, config/dependencies.yml, lib/packager.js, templates/gax/python/README.rst.mustache, templates/gax/python/docs/conf.py.mustache, templates/gax/python/docs/index.rst.mustache, templates/gax/python/requirements.txt.mustache, templates/gax/python/setup.py.mustache, templates/python/setup.py.mustache, test/fixtures/python/setup.py, test/packager.js
* Added upper-bounds to most packages, except our `grpc-google-*` packages, which require a bit more logic (https://github.com/googleapis/packman/issues/119).
* Protects us against future breaking changes in our dependencies
=> Add upper bound logic to Python packages

config/api_defaults.yml, config/dependencies.yml
Self-approving these version bumps. FYI @geigerj
=> Bump Python to 0.10.0, and GAX dependency to 0.14.1

templates/gax/nodejs/package.json.mustache
lodash.union will be added only when there are multiple services
in the API, but the template is wrong so that the trailing comma
is included in the dependency list if single service API, which
leads to an invalid JSON.
=> Remove the trailing comma if singleFile.

templates/gax/nodejs/index.js.mustache, test/fixtures/gax/nodejs-single/nodejs/package.json, test/fixtures/gax/nodejs-single/nodejs/src/v2/index.js, test/packager.js
- mustache does not allow accessing through square brackets.
. with number (.0) works fine.
- added test case to verify this and #131.
=> Fix nodejs generation of index.js

templates/gax/python/docs/conf.py.mustache, templates/gax/python/docs/index.rst.mustache, templates/gax/python/docs/starting.rst.mustache
This results in, for example, bad URL links.
=> Don't HTML encode in Python doc templates

templates/python/PUBLISHING.rst
Grammar fix as pointed out in [googleapis/api-client-staging/pull/21](https://github.com/googleapis/api-client-staging/pull/21)
=> Fixed typo in python publishing readme.

config/dependencies.yml, templates/gax/nodejs/package.json.mustache, test/fixtures/gax/nodejs-single/nodejs/package.json, test/fixtures/gax/nodejs/package.json
- the new codegen relies on gax-nodejs 0.7.0 --
updating the package version
- arguejs is not used anymore in the new codegen.
=> Update the gax/nodejs template.

config/api_defaults.yml
Breaking change in enum handling, so bump minor version.
=> Bump Python version

config/api_defaults.yml, config/dependencies.yml
=> Loosen oauth2client lower bound for Python

config/dependencies.yml
Theres a typo on 0.7.0 that causes errors for monitoring.
=> Update google protos version.

config/common_protos.yml, config/dependencies.yml
Have some updates to LRO and HTTP request.
PR for updating this package is separate: https://github.com/googleapis/api-client-staging/pull/50
=> Bump googleapis-common-protos version

bin/gen-api-package, config/dependencies.yml, lib/api_repo.js, lib/packager.js, templates/java/build-alt.gradle.mustache
- Adds a new command line argument to accept the gapic yaml file
- Updates the generated build.gradle file with the gapic yaml and resource name plugin
=> Support resource name generation for gRPC in Java

config/dependencies.yml
This seems to be more conventional for Python upper-bounds.
FYI @jonparrott
=> Shorten Python upper-bounds to two-number versions
