googleapis/packman

- package.json
Change-Id: I5b7286596e55fe8794779096d3df467b4f961809
> Bump version, fix the github repo link

- .travis.yml
- package.json
Change-Id: Ib8dda38e97d167979eac7556bf6367ee0bfb066f
> Add an npm coverage command; use it from travis

- package.json
This allows
```sh
npm version <semver-version>|patch|
```
to work
> Add npm command for release prepartion

- test/api_repo.js
This is to be submitted after #9
> Refactor tests simplify should fail should pass

- package.json
Change-Id: I6ec85727fdb323a6f15fd9b64dffbe1308ca6bf5
> Bump to version 0.6.0

- config/api_defaults.yml
- lib/api_repo.js
> Make package semvers language-specific

- lib/api_repo.js
- templates/gax/python/README.rst.mustache
- templates/gax/python/docs/index.rst.mustache
- templates/gax/python/docs/starting.rst.mustache
- templates/gax/python/requirements.txt.mustache
- templates/gax/python/setup.py.mustache
Change-Id: I983656c966930e0c2b123bf3f9ad9b72ae854ad1
> Improve gax-python package documentation

- config/api_defaults.yml
- config/dependencies.yml
Change-Id: Ib97de75d7b2d08a35bd39201a660135d53a1e250
> Update python api config

- config/dependencies.yml
> Update GAX dependency version for Python, Ruby

- .gitignore
- config/api_defaults.yml
- templates/gax/python/MANIFEST.in
- templates/gax/python/setup.py.mustache
- templates/gax/python/tox.ini
- templates/python/setup.py.mustache
- test/fixtures/python/setup.py
Fix the version number, the development status, and some packaging details
> Fix various packaging issues for Python

- .eslintrc.yml
- .jshintrc
- lib/api_repo.js
- lib/config.js
- lib/packager.js
- package.json
- test/.eslintrc.yml
- test/api_repo.js
- test/config.js
- test/packager.js
This also includes style fixes found by ESLint.
Fixes #62.
> Switch JSHint to ESLint style checker.

- package.json
What's new
- Fix Java protoc version.
> Bump up the version number to 0.7.3 for release.

- lib/api_repo.js
- lib/config.js
- lib/packager.js
Use hyphen between param and description.
> Change jsdoc style

- config/api_defaults.yml
- config/dependencies.yml
- package.json
For new release incorporating the HTML escaping fix.
> Bump the version

- templates/java/build-alt.gradle.mustache
- templates/java/build.gradle.mustache
- test/fixtures/java/build.gradle
The group ID should be com.google.api.grpc
> Fix group ID typo in build file.

- templates/java/PUBLISHING.md
- templates/java/build-alt.gradle.mustache
I was getting annoyed that uploadArchives silently did nothing when I didn't pass in the right thing.
> Java template enhancements

- package.json
This includes the fix for nodejs.
> Update packman version to 0.8.5.

- config/dependencies.yml
See also: https://github.com/googleapis/gax-ruby/pull/43
> Update ruby dependencies

- config/api_defaults.yml
- config/dependencies.yml
To be merged after https://github.com/googleapis/toolkit/pull/756
> Update configuration for new GAX release

- README.md
- package.json
New release includes support for Java resource name generation
Update README with new command line args
> Update packman version to 0.8.6

- templates/gax/nodejs/README.md.mustache
- templates/gax/ruby/README.md.mustache
- test/fixtures/gax/nodejs/README.md
Fix typo in README.md.mustache
> Fix extra open bracket in README.md.mustache

- templates/gax/ruby/README.md.mustache
- templates/gax/ruby/gemspec.mustache
- templates/ruby/gemspec.mustache
- test/fixtures/ruby/README.md
- test/fixtures/ruby/packager-unittest-v2.gemspec
> Automation fix to remove `-vx` from ruby generated files
